export const videoGames = [
    { name: "Pong", releaseYear: 1972, genre: "Arcade", creator: "Atari" },
    { name: "Space Invaders", releaseYear: 1978, genre: "Shooter", creator: "Taito" },
    { name: "Pac-Man", releaseYear: 1980, genre: "Arcade", creator: "Namco" },
    { name: "Donkey Kong", releaseYear: 1981, genre: "Platformer", creator: "Nintendo" },
    { name: "Mario Bros.", releaseYear: 1983, genre: "Platformer", creator: "Nintendo" },
    { name: "Tetris", releaseYear: 1984, genre: "Puzzle", creator: "Alexey Pajitnov" },
    { name: "Super Mario Bros.", releaseYear: 1985, genre: "Platformer", creator: "Nintendo" },
    { name: "The Legend of Zelda", releaseYear: 1986, genre: "Action-Adventure", creator: "Nintendo" },
    { name: "Metroid", releaseYear: 1986, genre: "Action-Adventure", creator: "Nintendo" },
    { name: "Castlevania", releaseYear: 1986, genre: "Action", creator: "Konami" },
    { name: "Contra", releaseYear: 1987, genre: "Shooter", creator: "Konami" },
    { name: "Mega Man", releaseYear: 1987, genre: "Platformer", creator: "Capcom" },
    { name: "Final Fantasy", releaseYear: 1987, genre: "RPG", creator: "Square" },
    { name: "Street Fighter", releaseYear: 1987, genre: "Fighting", creator: "Capcom" },
    { name: "Prince of Persia", releaseYear: 1989, genre: "Platformer", creator: "Jordan Mechner" },
    { name: "SimCity", releaseYear: 1989, genre: "Simulation", creator: "Maxis" },
    { name: "Golden Axe", releaseYear: 1989, genre: "Beat 'em up", creator: "Sega" },
    { name: "Dr. Mario", releaseYear: 1990, genre: "Puzzle", creator: "Nintendo" },
    { name: "F-Zero", releaseYear: 1990, genre: "Racing", creator: "Nintendo" },
    { name: "Sonic the Hedgehog", releaseYear: 1991, genre: "Platformer", creator: "Sega" },
    { name: "Street Fighter II", releaseYear: 1991, genre: "Fighting", creator: "Capcom" },
    { name: "Mortal Kombat", releaseYear: 1992, genre: "Fighting", creator: "Midway" },
    { name: "Wolfenstein 3D", releaseYear: 1992, genre: "Shooter", creator: "id Software" },
    { name: "Star Fox", releaseYear: 1993, genre: "Shooter", creator: "Nintendo" },
    { name: "DOOM", releaseYear: 1993, genre: "Shooter", creator: "id Software" },
    { name: "Day of the Tentacle", releaseYear: 1993, genre: "Adventure", creator: "LucasArts" },
    { name: "EarthBound", releaseYear: 1994, genre: "RPG", creator: "Nintendo" },
    { name: "Donkey Kong Country", releaseYear: 1994, genre: "Platformer", creator: "Rare" },
    { name: "Tekken", releaseYear: 1994, genre: "Fighting", creator: "Namco" },
    { name: "Chrono Trigger", releaseYear: 1995, genre: "RPG", creator: "Square" },
    { name: "Command & Conquer", releaseYear: 1995, genre: "Strategy", creator: "Westwood Studios" },
    { name: "Warcraft II", releaseYear: 1995, genre: "Strategy", creator: "Blizzard" },
    { name: "Super Mario 64", releaseYear: 1996, genre: "Platformer", creator: "Nintendo" },
    { name: "Quake", releaseYear: 1996, genre: "Shooter", creator: "id Software" },
    { name: "Tomb Raider", releaseYear: 1996, genre: "Action-Adventure", creator: "Core Design" },
    { name: "Diablo", releaseYear: 1996, genre: "RPG", creator: "Blizzard" },
    { name: "Crash Bandicoot", releaseYear: 1996, genre: "Platformer", creator: "Naughty Dog" },
    { name: "GoldenEye 007", releaseYear: 1997, genre: "Shooter", creator: "Rare" },
    { name: "Final Fantasy VII", releaseYear: 1997, genre: "RPG", creator: "Square" },
    { name: "Castlevania: Symphony of the Night", releaseYear: 1997, genre: "Action-Adventure", creator: "Konami" },
    { name: "StarCraft", releaseYear: 1998, genre: "Strategy", creator: "Blizzard" },
    { name: "Banjo-Kazooie", releaseYear: 1998, genre: "Platformer", creator: "Rare" },
    { name: "Half-Life", releaseYear: 1998, genre: "Shooter", creator: "Valve" },
    { name: "Metal Gear Solid", releaseYear: 1998, genre: "Stealth", creator: "Konami" },
    { name: "The Legend of Zelda: Ocarina of Time", releaseYear: 1998, genre: "Action-Adventure", creator: "Nintendo" },
    { name: "Counter-Strike", releaseYear: 1999, genre: "Shooter", creator: "Valve" },
    { name: "Super Smash Bros.", releaseYear: 1999, genre: "Fighting", creator: "Nintendo" },
    { name: "Tony Hawk's Pro Skater", releaseYear: 1999, genre: "Sports", creator: "Neversoft" },
    { name: "The Sims", releaseYear: 2000, genre: "Simulation", creator: "Maxis" },
    { name: "Diablo II", releaseYear: 2000, genre: "RPG", creator: "Blizzard" },
    { name: "Deus Ex", releaseYear: 2000, genre: "RPG", creator: "Ion Storm" },
    { name: "Halo: Combat Evolved", releaseYear: 2001, genre: "Shooter", creator: "Bungie" },
    { name: "Super Smash Bros. Melee", releaseYear: 2001, genre: "Fighting", creator: "Nintendo" },
    { name: "Grand Theft Auto III", releaseYear: 2001, genre: "Action-Adventure", creator: "Rockstar Games" },
    { name: "Jak and Daxter", releaseYear: 2001, genre: "Platformer", creator: "Naughty Dog" },
    { name: "Metroid Prime", releaseYear: 2002, genre: "Action-Adventure", creator: "Retro Studios" },
    { name: "Kingdom Hearts", releaseYear: 2002, genre: "RPG", creator: "Square Enix" },
    { name: "Battlefield 1942", releaseYear: 2002, genre: "Shooter", creator: "DICE" },
    { name: "Call of Duty", releaseYear: 2003, genre: "Shooter", creator: "Infinity Ward" },
    { name: "Prince of Persia: The Sands of Time", releaseYear: 2003, genre: "Action-Adventure", creator: "Ubisoft" },
    { name: "Beyond Good & Evil", releaseYear: 2003, genre: "Action-Adventure", creator: "Ubisoft" },
    { name: "World of Warcraft", releaseYear: 2004, genre: "MMORPG", creator: "Blizzard" },
    { name: "Half-Life 2", releaseYear: 2004, genre: "Shooter", creator: "Valve" },
    { name: "Far Cry", releaseYear: 2004, genre: "Shooter", creator: "Crytek" },
    { name: "God of War", releaseYear: 2005, genre: "Action", creator: "Santa Monica Studio" },
    { name: "Shadow of the Colossus", releaseYear: 2005, genre: "Action-Adventure", creator: "Team Ico" },
    { name: "Resident Evil 4", releaseYear: 2005, genre: "Horror", creator: "Capcom" },
    { name: "The Elder Scrolls IV: Oblivion", releaseYear: 2006, genre: "RPG", creator: "Bethesda" },
    { name: "Gears of War", releaseYear: 2006, genre: "Shooter", creator: "Epic Games" },
    { name: "Wii Sports", releaseYear: 2006, genre: "Sports", creator: "Nintendo" },
    { name: "The Legend of Zelda: Twilight Princess", releaseYear: 2006, genre: "Action-Adventure", creator: "Nintendo" },
    { name: "BioShock", releaseYear: 2007, genre: "Shooter", creator: "2K Games" },
    { name: "Portal", releaseYear: 2007, genre: "Puzzle", creator: "Valve" },
    { name: "Uncharted: Drake's Fortune", releaseYear: 2007, genre: "Action-Adventure", creator: "Naughty Dog" },
    { name: "Call of Duty 4: Modern Warfare", releaseYear: 2007, genre: "Shooter", creator: "Infinity Ward" },
    { name: "Super Mario Galaxy", releaseYear: 2007, genre: "Platformer", creator: "Nintendo" },
    { name: "Assassin's Creed", releaseYear: 2007, genre: "Action-Adventure", creator: "Ubisoft" },
    { name: "LittleBigPlanet", releaseYear: 2008, genre: "Platformer", creator: "Media Molecule" },
    { name: "Fallout 3", releaseYear: 2008, genre: "RPG", creator: "Bethesda" },
    { name: "Left 4 Dead", releaseYear: 2008, genre: "Shooter", creator: "Valve" },
    { name: "Minecraft", releaseYear: 2009, genre: "Sandbox", creator: "Mojang" },
    { name: "Angry Birds", releaseYear: 2009, genre: "Puzzle", creator: "Rovio" },
    { name: "League of Legends", releaseYear: 2009, genre: "MOBA", creator: "Riot Games" },
    { name: "Demon's Souls", releaseYear: 2009, genre: "RPG", creator: "FromSoftware" },
    { name: "Red Dead Redemption", releaseYear: 2010, genre: "Action-Adventure", creator: "Rockstar Games" },
    { name: "Mass Effect 2", releaseYear: 2010, genre: "RPG", creator: "BioWare" },
    { name: "StarCraft II", releaseYear: 2010, genre: "Strategy", creator: "Blizzard" },
    { name: "Dark Souls", releaseYear: 2011, genre: "RPG", creator: "FromSoftware" },
    { name: "The Elder Scrolls V: Skyrim", releaseYear: 2011, genre: "RPG", creator: "Bethesda" },
    { name: "Terraria", releaseYear: 2011, genre: "Sandbox", creator: "Re-Logic" },
    { name: "The Last of Us", releaseYear: 2013, genre: "Action-Adventure", creator: "Naughty Dog" },
    { name: "Grand Theft Auto V", releaseYear: 2013, genre: "Action-Adventure", creator: "Rockstar Games" },
    { name: "Overwatch", releaseYear: 2016, genre: "Shooter", creator: "Blizzard" },
    { name: "Fortnite", releaseYear: 2017, genre: "Battle Royale", creator: "Epic Games" },
    { name: "PlayerUnknown's Battlegrounds", releaseYear: 2017, genre: "Battle Royale", creator: "PUBG Corporation" },
    { name: "The Legend of Zelda: Breath of the Wild", releaseYear: 2017, genre: "Action-Adventure", creator: "Nintendo" },
    { name: "God of War", releaseYear: 2018, genre: "Action-Adventure", creator: "Santa Monica Studio" },
    { name: "Among Us", releaseYear: 2018, genre: "Party", creator: "Innersloth" },
    { name: "Hades", releaseYear: 2020, genre: "Roguelike", creator: "Supergiant Games" },
    { name: "Animal Crossing: New Horizons", releaseYear: 2020, genre: "Simulation", creator: "Nintendo" },
    { name: "Elden Ring", releaseYear: 2022, genre: "RPG", creator: "FromSoftware" },
    { name: "Baldur's Gate 3", releaseYear: 2023, genre: "RPG", creator: "Larian Studios" }
];

